In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
apps = pd.read_excel(r"C:\Users\admin\Downloads\Google Play Store Analysis\googleplaystore.xlsx")
reviews = pd.read_excel(r"C:\Users\admin\Downloads\Google Play Store Analysis\googleplaystore_user_reviews.xlsx")

In [5]:
apps.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [4]:
apps.shape

(10841, 13)

In [10]:
apps.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [11]:
apps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [22]:
apps['Reviews'] = pd.to_numeric(apps['Reviews'],errors='coerce')

In [24]:
apps['Rating'] = pd.to_numeric(apps['Rating'],errors='coerce')

In [35]:
apps['Installs'] = apps['Installs'].astype(str)
apps['Installs'] = apps['Installs'].str.replace(',','',regex=False)
apps['Installs'] = apps['Installs'].str.replace(',','',regex=False)
apps['Installs'] = pd.to_numeric(apps['Installs'],errors='coerce')

In [37]:
apps['Price'] = apps['Price'].astype(str)
apps['Price'] = apps['Price'].str.replace('$','',regex=False)
apps['Price'] = pd.to_numeric(apps['Price'],errors='coerce')

In [38]:
apps[['Installs', 'Price', 'Size']].head(10)

   Installs  Price  Size
0       NaN    0.0   19M
1       NaN    0.0   14M
2       NaN    0.0  8.7M
3       NaN    0.0   25M
4       NaN    0.0  2.8M
5       NaN    0.0  5.6M
6       NaN    0.0   19M
7       NaN    0.0   29M
8       NaN    0.0   33M
9       NaN    0.0  3.1M

In [33]:
apps.describe(include='all')

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10357,10358,8893.000000,1.035700e+04,10358,0.0,10357,10358.0,10357,10358,10358,10350,10355
unique,9659,34,NaN,NaN,462,NaN,3,93.0,6,120,1378,2784,33
top,ROBLOX,FAMILY,NaN,NaN,Varies with device,NaN,Free,0.0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1943,NaN,NaN,1526,NaN,9591,9592.0,8382,842,298,1302,2379
mean,NaN,NaN,4.189542,4.059046e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.545452,2.696778e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,3.200000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,4.300000,1.680000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,4.500000,4.641600e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,19.000000,7.815831e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#handle missing values
apps.isnull().sum()

App                  1
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [16]:
apps["Rating"] = apps["Rating"].fillna(apps["Rating"].median())

In [14]:
#duplicates
apps.duplicated().sum()

np.int64(483)

In [18]:
#remove duplicates
apps = apps.drop_duplicates()

In [7]:
#convert dates
apps['Last Updated'] = pd.to_datetime(apps['Last Updated'],errors = 'coerce')

In [14]:
#handle size coloumn
def convert_size(Size):
    if pd.isna(Size):
        return np.nan

    if Size =="Varies with device":
        return np.nan
    
    Size = str(Size)

    if Size.endswith("M"):
        return float(Size[:1])

    elif Size.endswith("k"):
        return float(Size[:1])/1024

        return np.nan
apps["Size"] = apps["Size"].apply(convert_size)

In [19]:
apps.to_excel("Googleplaystore_cleaned.xlsx",index=False)